site_name: YingweiGuo's Notes
     

theme:
  #logo: assets/logo.svg
  #favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
    #logo: bootstrap/envelope-paper

#  logo: assets/logo.png  :pushpin:
#  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.instant
#    - navigation.sections
    - toc.follow
#    - toc.integrate
    - announce.dismiss
    - navigation.footer
    - content.code.copy
  name: material
  custom_dir: overrides
  logo: assets/images/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - blog:
      post_readtime: true
      categories: true
      blog_toc: true
      post_url_format: "{slug}"
      categories_url_format: "category/{slug}"
      post_excerpt: optional
      archive_toc: true
      categories_toc: true
  - tags:
      tags_file: tags.md
  #- mkdocs-jupyter
  # 视频插件
  - mkdocs-video:
      is_video: true
      video_muted: false
      video_controls: true
      video_autoplay: false
  # 图片放大
  - glightbox:
      effect: zoom
      zoomable: true
      draggable: true
      skip_classes:
        - nonzoom
  # 更新时间显示
  - git-revision-date-localized:
      enable_creation_date: true
  - search: {}
  - encryptcontent: 
      password_button: True
      #global_password: 'password'
      



#nav: 
#  - Home: index.md
#  - Programing: 
#    - Linux: 01.programing/01.Linux
#    - Python: 01.programing/02.Python
#  - Bioinfomatics: 02.Bioinfomatics
#  - Research: 03.Research
#  - Tags: tags.md
#  - About: 04.About/about.md



#extra:
  #consent:
  #  title: Cookie consent
  #  description: >- 
  #    We use cookies to recognize your repeated visits and preferences, as well
  #    as to measure the effectiveness of our documentation and whether users
  #    find what they're searching for. With your consent, you're helping us to
  #    make our documentation better.
  #version:
    #provider: mike  # 版本控制

repo_url: https://github.com/guoyingwei6/notes
repo_name: guoyingwei6/notes
copyright: Copyright &copy; 2023 Yingwei Guo

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight: # 代码块高亮
     auto_title: true # 显示编程语言名称
  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      #emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #options:
        #custom_icons:
          #- overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - attr_list
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  # 鼠标点击特效
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/maodian.js
