site_name: YingweiGuo's Notes

theme:
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - navigation.top
    - navigation.instant
    - navigation.sections
    - toc.follow
    - toc.integrate
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode



#nav: 
#  - Home: index.md
#  - Programing:
#    - Programing/index.md
#    - Linux: Programing/Linux/linux.md
#    - Python: 
#      - Basic: Programing/Python/basic.md
#  - Bioinfomatics:
#    - Bioinfomatics/index.md
#    - Knowledge: 
#      - Evolution: Bioinfomatics/Knowledge/Evolution/yanhua.md
#    - Technology: 
#      - Format: Bioinfomatics/Knowledge/Technology/format.md
#  - About: about.md

extra:
  version:
    provider: mike
    
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde